# 직접 구현하는 방법  - 패키지 안쓰고.
 - 분석가는 직접 할 줄 알아야 함. 

In [32]:
#인코딩 대상 단어를 담은 리스트 
word_ls = ['원숭이','바나나','사과','코끼리']

In [40]:
from collections import defaultdict
import numpy as np

# {단어 : 인덱스} 사전구축!
word2id_dic = defaultdict(lambda :len(word2id_dic))    #제한없이!

for word in word_ls :
    word2id_dic[word]
    
# 고유단어 갯수 : 4개
n_unique_words = len(word2id_dic)

# 원핫 벡터를 만들기 위해서 비어있는 벡터 생성
one_hot_vectors = np.zeros((len(word_ls), n_unique_words))

# 단어 고유 인덱스
for i,word in enumerate(word_ls) :
    index = word2id_dic[word]
    one_hot_vectors[i,index] += 1   #고유 인덱스에 1을 더해준다
    
one_hot_vectors

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 이제 패키지로 써보자

# https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html
여기서 실습 코드를 가져옴

In [68]:
word_ls 

['원숭이', '바나나', '사과', '코끼리']

In [46]:
! pip install sklearn

In [69]:
# sklearn을 활용한 one-hot encoding
from numpy import array
from numpy import argmax      #큰 값부터 가져오는 기능
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# 예제 데이터 배열
values = array(word_ls)
values


array(['원숭이', '바나나', '사과', '코끼리'], dtype='<U3')

In [70]:
# 문자열에 숫자를 붙임
label_enc = LabelEncoder() # 선언하는 것임
int_enc = label_enc.fit_transform(values)  # 이건 컴퓨터에 fit하도록 알아서 설정하는 거임.
int_enc

array([2, 0, 1, 3], dtype=int64)

In [71]:
# binary encode
onehot_enc = OneHotEncoder(sparse=False)   #True로 하면 결과가 행렬로나오고 false는 배열로 나오는 차이.
int_enc = int_enc.reshape(len(int_enc),1)   #  n : 1 matrix로 변환함
onehot_enc = onehot_enc.fit_transform(int_enc)   # 분명 int_enc그 2013형태로 나왔을 것임
onehot_enc

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]])